### PR TITLE
fix: Add gradle-wrapper.jar to enable the wrapper scripts again

### PR DESCRIPTION
**Pull request by fezno**
It's sad it there are gradle wrapper scripts that suggest to use the also on the command line and they are not working. Just the jar file is missing, probably due to the overall .gitignore rules.

### CODE REVIEW

**Comment by L7R7** [comment]
I'm not sure if I get you right and I also didn't test that yet, but isn't the jar file supposed to be downloaded automatically if it's missing? I think that's also the reason why it is ignored.

**Comment by BeneStem** [comment]
Yes, Leo, you are correct.
But I think this might be an issue due to jdk10 or sth.
Yesterday I started a TravisCI integration which had the exact same problem… :/

**Comment by BeneStem** [comment]
I will release a new version this evening.
Needed to wait for https://issues.sonatype.org/browse/OSSRH-39172 to be fixed.
This is now done. So I can upload my new library

**Comment by L7R7** [comment]
Will this issue be fixed with the new version? Or do we still need a solution for that?

**Comment by BeneStem** [comment]
Probably not :/
Haven’t found the time to attend this issue yet.

**Comment by fezno** [comment]
Leo, Bene, the gradle-wrapper.jar file will never be downloaded during the build. It’s the code to download gradle. But you can generate it via the gradle wrapper task. So to bootstrap and keep the gradlew scripts it’s required. This has nothing to do with jdk 10 :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BeneStem** [comment]
Ah, you are right...
I myself am actually not using the wrapper at all. I am using globally installed gradle.
That's why I don't know much about it...
Anyways, should be fixed now :P

**Pull request closed without merging**
